// const internships =[
//   {
//     id: 0,
//     title: "Tech Intern",
//     company: "Parihar India",
//     location: "Delhi",
//     duration: "3 Months",
//     stipend: 5000,
//     posted: "3 weeks",
//     type: "Internship with job offer",
//   },
//   {
//     title: "Design Intern",
//     company: "Parihar India",
//     location: "Delhi",
//     duration: "3 Months",
//     stipend: 10000,
//     posted: "3 weeks",
//     type: "Internship with job offer",
//   },
//   {
//     title: "Research Intern",
//     company: "Parihar India",
//     location: "Delhi",
//     duration: "3 Months",
//     stipend: 10000,
//     posted: "5 days",
//     type: "Actively hiring",
//   },
//   {
//     title: "Marketing Intern",
//     company: "Parihar India",
//     location: "Delhi",
//     duration: "3 Months",
//     stipend: 12000,
//     posted: "6 days",
//     type: "Internship with job offer",
//   },
// ];

// export default internships;
// Sample internship data with additional properties for filtering
const internships = [
  {
    title: "Tech Intern",
    company: "Parihar India",
    location: "Delhi",
    duration: "3 Months",
    stipend: "5,000",
    stipendValue: 5000,
    posted: "3 weeks",
    isRemote: false,
    isPartTime: false,
    skills: ["JavaScript", "React", "Node.js"],
    description: "Join our tech team to work on exciting projects and gain hands-on experience.",
  },
  {
    title: "Design Intern",
    company: "Parihar India",
    location: "Delhi",
    duration: "3 Months",
    stipend: "10,000",
    stipendValue: 10000,
    posted: "3 weeks",
    isRemote: true,
    isPartTime: false,
    skills: ["Figma", "Adobe XD", "UI/UX"],
    description: "Design beautiful interfaces for our products and collaborate with our product team.",
  },
  {
    title: "Research Intern",
    company: "Parihar India",
    location: "Delhi",
    duration: "3 Months",
    stipend: "10,000",
    stipendValue: 10000,
    posted: "5 days",
    isRemote: false,
    isPartTime: true,
    skills: ["Data Analysis", "Research", "Documentation"],
    description: "Conduct market research and help us understand our customers better.",
  },
  {
    title: "Marketing Intern",
    company: "Parihar India",
    location: "Delhi",
    duration: "3 Months",
    stipend: "12,000",
    stipendValue: 12000,
    posted: "6 days",
    isRemote: true,
    isPartTime: false,
    skills: ["Social Media", "Content Writing", "SEO"],
    description: "Help us grow our online presence and reach more customers.",
  },
  {
    title: "Business Development Intern",
    company: "Parihar India",
    location: "Mumbai",
    duration: "6 Months",
    stipend: "15,000",
    stipendValue: 15000,
    posted: "1 week",
    isRemote: false,
    isPartTime: false,
    skills: ["Sales", "Communication", "Negotiation"],
    description: "Help us expand our business and reach new clients.",
  },
  {
    title: "Content Writing Intern",
    company: "Parihar India",
    location: "Bangalore",
    duration: "2 Months",
    stipend: "8,000",
    stipendValue: 8000,
    posted: "2 days",
    isRemote: true,
    isPartTime: true,
    skills: ["Writing", "Editing", "SEO"],
    description: "Create engaging content for our blog and social media channels.",
  },
  {
    title: "Data Science Intern",
    company: "Parihar India",
    location: "Hyderabad",
    duration: "4 Months",
    stipend: "18,000",
    stipendValue: 18000,
    posted: "1 day",
    isRemote: false,
    isPartTime: false,
    skills: ["Python", "Machine Learning", "Data Analysis"],
    description: "Work on real-world data problems and help us make data-driven decisions.",
  },
]

export default internships
