const courses = [
  {
    id: 0,
    title: "Web Development",
    company: "Internshala Trainings",
    location: "Online",
    duration: "6 Weeks",
    fees: 3499,
    posted: "2 days",
    type: "Beginner Friendly",
  },
  {
    id: 1,
    title: "Data Science",
    company: "Internshala Trainings",
    location: "Online",
    duration: "8 Weeks",
    fees: 4499,
    posted: "5 days",
    type: "Certificate Course",
  },
  {
    id: 2,
    title: "Python Programming",
    company: "Internshala Trainings",
    location: "Online",
    duration: "6 Weeks",
    fees: 2999,
    posted: "1 week",
    type: "Project Based",
  },
  {
    id: 3,
    title: "Digital Marketing",
    company: "Internshala Trainings",
    location: "Online",
    duration: "6 Weeks",
    fees: 3499,
    posted: "3 days",
    type: "Beginner Friendly",
  },
  {
    id: 4,
    title: "Android App Development",
    company: "Internshala Trainings",
    location: "Online",
    duration: "8 Weeks",
    fees: 4499,
    posted: "4 days",
    type: "Certificate Course",
  },
  {
    id: 5,
    title: "UI/UX Design",
    company: "Internshala Trainings",
    location: "Online",
    duration: "6 Weeks",
    fees: 3799,
    posted: "2 weeks",
    type: "Project Based",
  },
  {
    id: 6,
    title: "Ethical Hacking",
    company: "Internshala Trainings",
    location: "Online",
    duration: "8 Weeks",
    fees: 4999,
    posted: "1 day",
    type: "Certificate Course",
  },
  {
    id: 7,
    title: "AutoCAD for Engineers",
    company: "Internshala Trainings",
    location: "Online",
    duration: "6 Weeks",
    fees: 3299,
    posted: "6 days",
    type: "Industry Oriented",
  },
];

export default courses;
