// const jobs =[
//   {
//     id: 0,
//     title: "Tech Intern",
//     company: "Parihar India",
//     location: "Delhi",
//     duration: "3 Months",
//     stipend: 5000,
//     posted: "3 weeks",
//     type: "Internship with job offer",
//   },
//   {
//     title: "Design Intern",
//     company: "Parihar India",
//     location: "Delhi",
//     duration: "3 Months",
//     stipend: 10000,
//     posted: "3 weeks",
//     type: "Internship with job offer",
//   },
//   {
//     title: "Research Intern",
//     company: "Parihar India",
//     location: "Delhi",
//     duration: "3 Months",
//     stipend: 10000,
//     posted: "5 days",
//     type: "Actively hiring",
//   },
//   {
//     title: "Marketing Intern",
//     company: "Parihar India",
//     location: "Delhi",
//     duration: "3 Months",
//     stipend: 12000,
//     posted: "6 days",
//     type: "Internship with job offer",
//   },
// ];

// export default jobs;

// Sample job data with additional properties for filtering
const jobs = [
  {
    title: "Frontend Developer",
    company: "TechCorp India",
    location: "Delhi",
    experience: "1-3 years",
    salary: "50,000",
    salaryValue: 50000,
    posted: "3 days",
    isRemote: false,
    isPartTime: false,
    skills: ["JavaScript", "React", "CSS"],
    description: "Join our team to build beautiful and responsive web applications.",
  },
  {
    title: "UX Designer",
    company: "DesignHub",
    location: "Bangalore",
    experience: "2-4 years",
    salary: "65,000",
    salaryValue: 65000,
    posted: "1 week",
    isRemote: true,
    isPartTime: false,
    skills: ["Figma", "Adobe XD", "UI/UX"],
    description: "Design beautiful interfaces for our products and collaborate with our product team.",
  },
  {
    title: "Data Analyst",
    company: "DataInsights",
    location: "Mumbai",
    experience: "0-2 years",
    salary: "45,000",
    salaryValue: 45000,
    posted: "2 days",
    isRemote: false,
    isPartTime: true,
    skills: ["SQL", "Excel", "Python"],
    description: "Analyze data and provide insights to help us make better business decisions.",
  },
  {
    title: "Digital Marketing Manager",
    company: "GrowthX",
    location: "Delhi",
    experience: "3-5 years",
    salary: "80,000",
    salaryValue: 80000,
    posted: "5 days",
    isRemote: true,
    isPartTime: false,
    skills: ["SEO", "SEM", "Social Media"],
    description: "Lead our digital marketing efforts to drive growth and engagement.",
  },
  {
    title: "Backend Developer",
    company: "CloudTech",
    location: "Hyderabad",
    experience: "2-5 years",
    salary: "70,000",
    salaryValue: 70000,
    posted: "1 day",
    isRemote: false,
    isPartTime: false,
    skills: ["Node.js", "MongoDB", "AWS"],
    description: "Build scalable and robust backend systems for our cloud-based products.",
  },
  {
    title: "Content Writer",
    company: "ContentLabs",
    location: "Pune",
    experience: "1-2 years",
    salary: "35,000",
    salaryValue: 35000,
    posted: "4 days",
    isRemote: true,
    isPartTime: true,
    skills: ["Copywriting", "SEO", "Editing"],
    description: "Create engaging content for our blog, website, and social media channels.",
  },
  {
    title: "Product Manager",
    company: "InnovateTech",
    location: "Bangalore",
    experience: "4-6 years",
    salary: "95,000",
    salaryValue: 95000,
    posted: "2 weeks",
    isRemote: false,
    isPartTime: false,
    skills: ["Product Strategy", "User Research", "Agile"],
    description: "Lead product development from concept to launch and drive continuous improvement.",
  },
]

export default jobs
