const jobsData = [
  {
    id: 1,
    title: "Content Operations",
    location: "Mumbai",
    stipend: "₹5,000-10,000/month",
    duration: "3 Months",
    hiringStatus: "Actively Hiring",
    views: '5k',
    daysLeft: '3',
    bgColor: 'bg-gradient-to-r from-purple-500 via-violet-500 to-blue-500',
    company: 'company 1',
    eligible: '12th Pass',
    img: 'https://th.bing.com/th/id/OIG3.80EN2JPNx7kp5VqoB5kz'
  },
  {
    id: 2,
    title: "Web Development",
    location: "Remote",
    stipend: "₹8,000-15,000/month",
    duration: "6 Months",
    hiringStatus: "Actively Hiring",
    views: '10k',
    daysLeft: '5',
    bgColor: 'bg-gradient-to-r from-[#ea8d8d] to-[#ff8c8c]',
    company: 'company 2',
    eligible: '12th Pass',
    img: 'https://th.bing.com/th/id/OIG3.80EN2JPNx7kp5VqoB5kz'
  },
  {
    id: 3,
    title: "Graphic Design",
    location: "Delhi",
    stipend: "₹10,000-12,000/month",
    duration: "2 Months",
    hiringStatus: "Actively Hiring",
    views: '1k',
    daysLeft: '1',
    bgColor: 'bg-gradient-to-r from-green-700 via-green-400 to-green-200',
    company: 'company 3',
    eligible: '12th Pass',
    img: 'https://th.bing.com/th/id/OIG3.80EN2JPNx7kp5VqoB5kz'
  },
  {
    id: 4,
    title: "Marketing Intern",
    location: "Bangalore",
    stipend: "₹7,000/month",
    duration: "4 Months",
    hiringStatus: "Actively Hiring",
    views: '800',
    daysLeft: '8',
    bgColor: 'bg-gradient-to-r from-[#17ead9] to-[#6078ea]',
    company: 'company 4',
    eligible: '12th Pass',
    img: 'https://th.bing.com/th/id/OIG3.80EN2JPNx7kp5VqoB5kz'
  },
  {
    id: 5,
    title: "Data Analysis",
    location: "Pune",
    stipend: "₹6,000-8,000/month",
    duration: "3 Months",
    hiringStatus: "Actively Hiring",
    views: '15k',
    daysLeft: '10',
    bgColor: 'bg-gradient-to-r from-purple-500 via-violet-500 to-blue-500',
    company: 'company 5',
    eligible: '12th Pass',
    img: 'https://th.bing.com/th/id/OIG3.80EN2JPNx7kp5VqoB5kz'
  },
  {
    id: 6,
    title: "Social Media Manager",
    location: "Remote",
    stipend: "₹5,000/month",
    duration: "1 Month",
    hiringStatus: "Actively Hiring",
    views: '5k',
    daysLeft: '4',
    bgColor: 'bg-gradient-to-r from-[#ea8d8d] to-[#ff8c8c]',
    company: 'company 6',
    eligible: '12th Pass',
    img: 'https://th.bing.com/th/id/OIG3.80EN2JPNx7kp5VqoB5kz'
  },
  {
    id: 7,
    image: "/path-to-your-image/newcard.png",
    title: "New Card",
    description: "Description of the new card",
  },
];

export default jobsData;
