const dummyDatabase = {
  users: [
    {
      id: 1,
      personalInfo: {
        firstName: "Aaditya",
        lastName: "Aggarwal",
        email: "aaditya.aggarwal@email.com",
        phone: "+91-9876543210",
        dateOfBirth: "2002-03-15",
        address: {
          street: "123 Tech Street",
          city: "Bangalore",
          state: "Karnataka",
          zipCode: "560001",
          country: "India",
        },
        profileImage: "/placeholder.svg?height=100&width=100",
      },
      academicInfo: {
        university: "Indian Institute of Technology",
        degree: "Bachelor of Technology",
        major: "Computer Science Engineering",
        year: "3rd Year",
        cgpa: 8.7,
        expectedGraduation: "2025-05-15",
      },
      internshipDetails: {
        internshipId: "INT-2025-001",
        title: "Frontend Developer Intern",
        department: "Engineering",
        supervisor: {
          name: "Priya Sharma",
          email: "priya.sharma@company.com",
          designation: "Senior Frontend Developer",
        },
        startDate: "2025-01-01",
        endDate: "2025-03-01",
        duration: 60, // days
        stipend: 25000, // monthly
        workMode: "Hybrid",
        location: "Bangalore, India",
      },
      skills: [
        { name: "React.js", level: 85, category: "Frontend" },
        { name: "JavaScript", level: 90, category: "Programming" },
        { name: "TypeScript", level: 75, category: "Programming" },
        { name: "HTML/CSS", level: 95, category: "Frontend" },
        { name: "Node.js", level: 70, category: "Backend" },
        { name: "Git", level: 80, category: "Tools" },
        { name: "Figma", level: 65, category: "Design" },
        { name: "MongoDB", level: 60, category: "Database" },
      ],
      tasks: [
        {
          id: 1,
          title: "Setup Development Environment",
          description: "Configure local development environment with React, Node.js, and necessary tools",
          category: "Setup",
          priority: "High",
          status: "completed",
          assignedDate: "2025-01-01",
          dueDate: "2025-01-03",
          completedDate: "2025-01-02",
          estimatedHours: 8,
          actualHours: 6,
          difficulty: "Easy",
          tags: ["setup", "environment", "tools"],
          feedback: "Excellent setup! Completed ahead of schedule with proper documentation.",
        },
        {
          id: 2,
          title: "Create Landing Page Component",
          description: "Design and develop a responsive landing page component using React and Tailwind CSS",
          category: "Development",
          priority: "Medium",
          status: "completed",
          assignedDate: "2025-01-03",
          dueDate: "2025-01-08",
          completedDate: "2025-01-07",
          estimatedHours: 16,
          actualHours: 14,
          difficulty: "Medium",
          tags: ["react", "frontend", "responsive"],
          feedback: "Great attention to detail in responsive design. Code quality is excellent.",
        },
        {
          id: 3,
          title: "Implement User Authentication",
          description: "Build secure user authentication system with login, signup, and password reset functionality",
          category: "Development",
          priority: "High",
          status: "completed",
          assignedDate: "2025-01-08",
          dueDate: "2025-01-15",
          completedDate: "2025-01-14",
          estimatedHours: 24,
          actualHours: 22,
          difficulty: "Hard",
          tags: ["authentication", "security", "backend"],
          feedback: "Solid implementation with proper security measures. Well documented code.",
        },
        {
          id: 4,
          title: "Build Dashboard Interface",
          description: "Create an interactive dashboard with data visualization and user management features",
          category: "Development",
          priority: "High",
          status: "in-progress",
          assignedDate: "2025-01-15",
          dueDate: "2025-01-22",
          completedDate: null,
          estimatedHours: 32,
          actualHours: 18,
          difficulty: "Hard",
          tags: ["dashboard", "visualization", "ui/ux"],
          feedback: null,
          progress: 65,
        },
        {
          id: 5,
          title: "Add Data Visualization Charts",
          description: "Integrate interactive charts and graphs using Chart.js or D3.js for data representation",
          category: "Development",
          priority: "Medium",
          status: "in-progress",
          assignedDate: "2025-01-20",
          dueDate: "2025-01-28",
          completedDate: null,
          estimatedHours: 20,
          actualHours: 8,
          difficulty: "Medium",
          tags: ["charts", "visualization", "data"],
          feedback: null,
          progress: 30,
        },
        {
          id: 6,
          title: "Implement Responsive Design",
          description: "Ensure all components are fully responsive across desktop, tablet, and mobile devices",
          category: "Development",
          priority: "Medium",
          status: "pending",
          assignedDate: "2025-01-25",
          dueDate: "2025-02-02",
          completedDate: null,
          estimatedHours: 16,
          actualHours: 0,
          difficulty: "Medium",
          tags: ["responsive", "mobile", "css"],
          feedback: null,
        },
        {
          id: 7,
          title: "Write Unit Tests",
          description:
            "Create comprehensive unit tests for all components and functions using Jest and React Testing Library",
          category: "Testing",
          priority: "Medium",
          status: "pending",
          assignedDate: "2025-01-28",
          dueDate: "2025-02-05",
          completedDate: null,
          estimatedHours: 24,
          actualHours: 0,
          difficulty: "Medium",
          tags: ["testing", "jest", "quality"],
          feedback: null,
        },
        {
          id: 8,
          title: "API Integration",
          description: "Integrate with external APIs for data fetching and third-party service connections",
          category: "Development",
          priority: "High",
          status: "pending",
          assignedDate: "2025-02-01",
          dueDate: "2025-02-08",
          completedDate: null,
          estimatedHours: 20,
          actualHours: 0,
          difficulty: "Hard",
          tags: ["api", "integration", "backend"],
          feedback: null,
        },
        {
          id: 9,
          title: "Performance Optimization",
          description: "Optimize application performance, implement lazy loading, and reduce bundle size",
          category: "Optimization",
          priority: "Low",
          status: "pending",
          assignedDate: "2025-02-08",
          dueDate: "2025-02-15",
          completedDate: null,
          estimatedHours: 16,
          actualHours: 0,
          difficulty: "Hard",
          tags: ["performance", "optimization", "lazy-loading"],
          feedback: null,
        },
        {
          id: 10,
          title: "Documentation & Deployment",
          description: "Create comprehensive documentation and deploy the application to production",
          category: "Documentation",
          priority: "Medium",
          status: "pending",
          assignedDate: "2025-02-15",
          dueDate: "2025-02-22",
          completedDate: null,
          estimatedHours: 12,
          actualHours: 0,
          difficulty: "Easy",
          tags: ["documentation", "deployment", "production"],
          feedback: null,
        },
      ],
      attendance: [
        { date: "2025-01-01", status: "present", hoursWorked: 8, checkIn: "09:00", checkOut: "17:00" },
        { date: "2025-01-02", status: "present", hoursWorked: 7.5, checkIn: "09:15", checkOut: "17:00" },
        { date: "2025-01-03", status: "present", hoursWorked: 8, checkIn: "09:00", checkOut: "17:00" },
        { date: "2025-01-04", status: "weekend", hoursWorked: 0 },
        { date: "2025-01-05", status: "weekend", hoursWorked: 0 },
        { date: "2025-01-06", status: "present", hoursWorked: 8, checkIn: "09:00", checkOut: "17:00" },
        { date: "2025-01-07", status: "present", hoursWorked: 8.5, checkIn: "08:45", checkOut: "17:15" },
        { date: "2025-01-08", status: "present", hoursWorked: 8, checkIn: "09:00", checkOut: "17:00" },
        { date: "2025-01-09", status: "present", hoursWorked: 7.5, checkIn: "09:30", checkOut: "17:00" },
        { date: "2025-01-10", status: "present", hoursWorked: 8, checkIn: "09:00", checkOut: "17:00" },
      ],
      performanceMetrics: {
        overallRating: 4.2,
        technicalSkills: 4.5,
        communication: 4.0,
        teamwork: 4.3,
        problemSolving: 4.4,
        timeManagement: 3.8,
        initiative: 4.1,
        codeQuality: 4.6,
        learningAbility: 4.7,
      },
      projects: [
        {
          id: 1,
          name: "E-commerce Dashboard",
          description: "A comprehensive admin dashboard for e-commerce management",
          status: "in-progress",
          startDate: "2025-01-01",
          technologies: ["React", "TypeScript", "Tailwind CSS", "Chart.js"],
          progress: 65,
          repository: "https://github.com/aaditya/ecommerce-dashboard",
        },
      ],
      achievements: [
        {
          id: 1,
          title: "Quick Learner",
          description: "Completed initial setup 2 days ahead of schedule",
          date: "2025-01-02",
          category: "Performance",
        },
        {
          id: 2,
          title: "Code Quality Champion",
          description: "Maintained 95%+ code quality score across all submissions",
          date: "2025-01-10",
          category: "Quality",
        },
      ],
      weeklyReports: [
        {
          week: 1,
          startDate: "2025-01-01",
          endDate: "2025-01-05",
          tasksCompleted: 2,
          hoursWorked: 31.5,
          productivity: 85,
          highlights: ["Setup completed efficiently", "First component delivered"],
          challenges: ["Learning new framework initially"],
        },
        {
          week: 2,
          startDate: "2025-01-06",
          endDate: "2025-01-12",
          tasksCompleted: 1,
          hoursWorked: 40,
          productivity: 78,
          highlights: ["Authentication system implemented"],
          challenges: ["Complex security requirements"],
        },
      ],
    },
  ],

  // Additional users can be added here
  companies: [
    {
      id: 1,
      name: "TechCorp Solutions",
      industry: "Software Development",
      size: "500-1000 employees",
      location: "Bangalore, India",
      website: "https://techcorp.com",
    },
  ],
}

// Helper function to get user data by ID
export const getUserById = (userId) => {
  return dummyDatabase.users.find((user) => user.id === userId)
}

// Helper function to get current user (for demo purposes, returns first user)
export const getCurrentUser = () => {
  return dummyDatabase.users[0]
}

export default dummyDatabase
